# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-29 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import videoprocessing.models
import videoprocessing.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creation', '0016_auto_20190918_0536'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_no', models.SmallIntegerField()),
                ('audio_chunk', models.FileField(storage=videoprocessing.storage.OverwriteStorage(), upload_to=videoprocessing.models.get_audio_chunk_path, validators=[videoprocessing.models.validate_audio])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='in_queue', max_length=10)),
                ('video', models.FileField(upload_to=videoprocessing.models.get_video_path, validators=[videoprocessing.models.validate_video])),
                ('subtitle', models.FileField(upload_to=videoprocessing.models.get_subtitle_path, validators=[videoprocessing.models.validate_subtitle])),
                ('total_chunks', models.SmallIntegerField(default=0)),
                ('processed_video', models.FileField(upload_to='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.Language')),
                ('tutorial_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.TutorialDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='videochunk',
            name='VideoTutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoprocessing.VideoTutorial'),
        ),
    ]
