# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-04 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0016_auto_20190918_0536'),
        ('videoprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotutorial',
            name='foss',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.CASCADE, to='creation.FossCategory'),
            preserve_default=False,
        ),
    ]
