version: "3"
services:
  # Django APP
  app: &app
    build:
      context: .
    network_mode: host
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  # Messaging Broker
  rabbitmq:
    image: rabbitmq:alpine
    network_mode: host
